name: Blog CI/CD

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'

jobs:
  build-production-macos:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [16.x]
        os: [windows-latest, macos-latest]
        fail-fast: false
    steps:
    - uses: actions/checkout@v2   # 第一步，检出仓库副本

    - name: Use Node.js ${{ matrix.node-version }} #规定node.js版本(可不配置)
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies  # 第二步，安装依赖
      run: npm install

    - name: build windows app
      if: matrix.os == 'windows-latest'
      run: npm run electron:build --if-present
 
    - name: build mac app
      if: matrix.os == 'macos-latest'
      run: npm run electron:build --if-present

    - name: Create Release # 创建Release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}-Demo
        release_name: Release ${{ steps.get_version.outputs.VERSION }}-Demo
        files: "build/**"
